# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 929b35219e81807cf80768b50b80ecd9aa2d8ca277e3acb8e252358539c87684c5e8ad17befe6f910efaaae55984fb4bba45cf71100a95f770483a5b6f77727e

test:
  secret_key_base: ffe1c19b25b25edc6a2104a3990c35d6deba1dfac08eb381aaaa7e12e3cb649948984d0f79c896e2a0b8aabb9547e3d57b8801772978ef5b9f4700d935458a45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
