#Instrument Choices
Instrument.create(name: "Alto Sax")
Instrument.create(name: "Baritone")
Instrument.create(name: "Baritone Sax")
Instrument.create(name: "Bass")
Instrument.create(name: "Bass Guitar")
Instrument.create(name: "Bassoon")
Instrument.create(name: "BBD")
Instrument.create(name: "Big Ten Flags")
Instrument.create(name: "Cello")
Instrument.create(name: "Clarinet")
Instrument.create(name: "Drum Set")
Instrument.create(name: "Drumline")
Instrument.create(name: "Euphonium")
Instrument.create(name: "Flute")
Instrument.create(name: "French Horn")
Instrument.create(name: "Gold Dusters")
Instrument.create(name: "Golden Silks")
Instrument.create(name: "Guitar")
Instrument.create(name: "Harp")
Instrument.create(name: "Jazz Vocal")
Instrument.create(name: "Mellophone")
Instrument.create(name: "Oboe")
Instrument.create(name: "Percussion")
Instrument.create(name: "Piano")
Instrument.create(name: "Piccolo")
Instrument.create(name: "Solo Twirlers")
Instrument.create(name: "Sousaphone")
Instrument.create(name: "Tenor Sax")
Instrument.create(name: "Trombone")
Instrument.create(name: "Trumpet")
Instrument.create(name: "Tuba")
Instrument.create(name: "Viola")
Instrument.create(name: "Violin")

#Ensemble Choices
Ensemble.create(name: "AAMB")
Ensemble.create(name: "Big Ten Flags")
Ensemble.create(name: "Concert")
Ensemble.create(name: "Golddusters")
Ensemble.create(name: "Golden Silks")
Ensemble.create(name: "Jazz")
Ensemble.create(name: "Orchestra")
Ensemble.create(name: "Percussion")
Ensemble.create(name: "Twirlers")
